#!/bin/sh

echo 'DROP DATABASE IF EXISTS yii2_gii_plus_tests;
CREATE DATABASE yii2_gii_plus_tests;' | mysql

DIR=$(dirname $0)

rm -frv $DIR/models/*
rm -frv $DIR/fixtures/*
rm -frv $DIR/tests/data/*

$DIR/yii migrate --interactive=0
$DIR/yii gii/base_model --interactive=0 --enableI18N=1
$DIR/yii gii/custom_model --interactive=0
$DIR/yii gii/base_model --interactive=0 --overwrite=1 --enableI18N=1
$DIR/yii gii/base_model --interactive=0 --overwrite=1 --enableI18N=1
$DIR/yii gii/fixture --interactive=0 --generateDataFile=1
$DIR/yii gii/fixture --interactive=0 --overwrite=1
